### ISSUE TITLE
Add new languages for Code Blocks

### ISSUE THREAD

**Issue by dotCore-off** [tbdscripts/documentation#2]
Yo.
I'd recommend **adding all needed languages as supported by the Code Blocks syntax highlighting**.
PHP **isn't supported** as of now, and I'm pretty sure Lua isn't either.

**Read that part of Docusaurus doc to learn more about it :** [Add a new language for Code Blocks](https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages).

ty ❤️

**Comment by LucaTanks** [comment]
Done, thanks :D
